services:
  - type: web
    name: void-z1
    runtime: docker
    plan: free
    healthCheckPath: /health
    autoDeploy: true
    # Docker build arguments and runtime environment variables
    # will be pulled from the 'supabase-credentials' Env Group.
    envVars:
      - fromGroup: supabase-credentials
      - key: PYTHON_VERSION
        value: 3.9 # Matching the Dockerfile
